# fly.toml app configuration file generated for dynamic-questionnaire on 2025-02-09T09:00:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dynamic-questionnaire'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
